name: mocpy-dev

channels:
- defaults
- conda-forge

dependencies:
- maturin
- astropy
- astroquery
- astropy-healpix # Optional dependency for boundaries notebook
- requests
- matplotlib # Used in fill and border
- networkx # Used in get_boundaries
