#!/bin/bash

# Install cargo 
curl https://sh.rustup.rs -sSf | sh -s -- -y
source $HOME/.cargo/env
# Install the MOCPy version from the remote repo
pip install .

# To use maturin develop, need to be in a virtualenv
# pip install . seem to work.
# > maturin develop --release
