#!/bin/bash

# Install cargo 
curl https://sh.rustup.rs -sSf | sh -s -- -y
export PATH="$HOME/.cargo/bin:$PATH"
# Install the MOCPy version from the remote repo
# ?? ./env/bin/pip install -r requirements.txt
# ?? maturin develop --release
pip install .
