#!/bin/bash

# Install cargo 
curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain nightly -y
export PATH="$HOME/.cargo/bin:$PATH"
# Install the MOCPy version from the remote repo
pip install .