name: check-old-rust-version

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  msrv-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cds-astro/ci-templates/.github/actions/minimal-rust-version-check@main