name: test-cov
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:

  # Perform tests with coverage
  test-cov:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout branch ${{ github.head_ref }}"
        uses: actions/checkout@v7
      - name: "Set up Python on Ubuntu"
        uses: actions/setup-python@v7
        with:
          python-version: 3.13
            # Test Rust code
      - name: "Test with coverage, build and test doc"
        run: |
          # Install virtualenv
          pip install virtualenv
          # Create and activate a new virtualenv
          virtualenv mocpy-env
          source mocpy-env/bin/activate
          # For debug purpose (see dependencies)
          cargo tree
          # Install maturin
          pip install maturin==1.12.4
          # Build and install mocpy
          maturin develop --release
          # Install pytest-cov, needed to test with coverage
          pip install .[dev,plots]
          pip install pytest-cov
          # Run test with coverage and doctests
          python -m pytest -v -s --doctest-modules python/mocpy --cov-report=term --cov=python/mocpy
